'use client';

import Link from 'next/link';
import { motion } from 'framer-motion';
import { ArrowRight, Box, CreditCard, Globe, Server, Activity, ShieldCheck, ChevronRight } from 'lucide-react';
import { AgentCard } from '@/components/AgentCard';
import { mockAgents } from '@/data/mock';

// A sophisticated animated geometric SVG background piece
const AnimatedNetworkSVG = () => {
  return (
    <div className="absolute inset-0 flex items-center justify-center opacity-[0.08] pointer-events-none overflow-hidden">
      <motion.svg
        width="100%"
        height="100%"
        viewBox="0 0 1000 600"
        preserveAspectRatio="xMidYMid slice"
        className="text-white"
        initial="hidden"
        animate="visible"
      >
        <motion.path
          d="M 200 100 L 800 200 L 900 500 L 300 550 L 100 350 Z"
          fill="none"
          stroke="currentColor"
          strokeWidth="1"
          variants={{
            hidden: { pathLength: 0, opacity: 0 },
            visible: { pathLength: 1, opacity: 1, transition: { duration: 3, ease: [0.16, 1, 0.3, 1] } }
          }}
        />
        <motion.path
          d="M 200 100 L 300 550 M 100 350 L 800 200 M 900 500 L 100 350"
          fill="none"
          stroke="currentColor"
          strokeWidth="0.5"
          variants={{
            hidden: { pathLength: 0, opacity: 0 },
            visible: { pathLength: 1, opacity: 0.5, transition: { duration: 3, delay: 0.5, ease: [0.16, 1, 0.3, 1] } }
          }}
        />
        <motion.circle
          cx="500" cy="300" r="200"
          fill="none" stroke="currentColor" strokeWidth="0.5" strokeDasharray="8 8"
          variants={{
            hidden: { scale: 0.8, opacity: 0 },
            visible: { scale: 1, opacity: 0.4, transition: { duration: 2.5, delay: 1, ease: [0.16, 1, 0.3, 1] } }
          }}
        />
        {/* Animated nodes */}
        {[
          { cx: 200, cy: 100 }, { cx: 800, cy: 200 }, { cx: 900, cy: 500 },
          { cx: 300, cy: 550 }, { cx: 100, cy: 350 }, { cx: 500, cy: 300 }
        ].map((node, i) => (
          <motion.circle
            key={i}
            cx={node.cx} cy={node.cy} r="3"
            fill="currentColor"
            variants={{
              hidden: { scale: 0, opacity: 0 },
              visible: { scale: 1, opacity: 1, transition: { duration: 1, delay: 2 + (i * 0.2) } }
            }}
          />
        ))}
      </motion.svg>
    </div>
  );
};

const categories = [
  { name: 'Image AI', icon: Box },
  { name: 'Voice AI', icon: Activity },
  { name: 'Productivity', icon: Server },
  { name: 'Coding', icon: ShieldCheck },
  { name: 'Marketing', icon: Globe },
];

const whySolana = [
  {
    icon: CreditCard,
    title: 'Sub-second Finality',
    description: 'Transactions process in milliseconds, providing immediate access to purchased agents without waiting for block confirmations.',
  },
  {
    icon: Activity,
    title: 'Minimal Overhead',
    description: 'Transaction fees are fractions of a cent, ensuring that creators retain the majority of the value generated by their work.',
  },
  {
    icon: Globe,
    title: 'Borderless Distribution',
    description: 'A globally accessible infrastructure that connects creators and users directly, bypassing traditional payment gateways.',
  },
];

export default function HomePage() {
  return (
    <div className="flex flex-col bg-[#09090b] selection:bg-white/10">
      {/* Hero */}
      <section className="relative min-h-[85vh] flex flex-col justify-center overflow-hidden bg-[#09090b]">
        <AnimatedNetworkSVG />
        
        <div className="relative z-10 container mx-auto px-6 max-w-6xl pt-20 pb-32">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8, ease: [0.16, 1, 0.3, 1] }}
          >
            <div className="inline-flex items-center gap-2 border border-white/5 bg-white/5 backdrop-blur-xl rounded-full px-4 py-1.5 mb-10 shadow-2xl">
              <span className="w-1.5 h-1.5 rounded-full bg-white animate-pulse shadow-[0_0_8px_rgba(255,255,255,0.8)]" />
              <span className="text-[10px] uppercase tracking-[0.2em] text-white font-bold">Network Protocol v1.0.4</span>
            </div>

            <h1 className="text-5xl md:text-7xl font-bold tracking-tight mb-8 text-white max-w-4xl leading-[1.05]">
              The Sovereign <br/>
              <span className="text-[#3f3f46]">Agent Network.</span>
            </h1>

            <p className="text-[#71717a] max-w-xl mb-12 text-lg md:text-xl leading-relaxed">
              Decentralized infrastructure for the distribution and monetization of autonomous AI agents. Built for scale on Solana.
            </p>

            <div className="flex flex-col sm:flex-row items-center gap-4">
              <Link
                href="/marketplace"
                className="w-full sm:w-auto flex items-center justify-center gap-3 px-8 py-4 rounded-md bg-white text-black hover:bg-zinc-200 transition-all duration-300 font-bold text-xs uppercase tracking-widest shadow-xl shadow-white/5"
              >
                Access Directory
                <ArrowRight className="w-4 h-4" />
              </Link>
              <Link
                href="/developer"
                className="w-full sm:w-auto flex items-center justify-center gap-3 px-8 py-4 rounded-md border border-white/10 bg-white/5 backdrop-blur-md hover:bg-white/10 text-white transition-all duration-300 font-bold text-xs uppercase tracking-widest"
              >
                Deploy Infrastructure
              </Link>
            </div>
          </motion.div>
        </div>
        
        <div className="absolute bottom-0 left-0 w-full h-64 bg-gradient-to-t from-[#09090b] to-transparent pointer-events-none" />
      </section>

      {/* Categories */}
      <section className="py-32 container mx-auto px-6 max-w-7xl border-t border-white/5">
        <div className="flex flex-col md:flex-row md:items-end justify-between mb-16 gap-6">
          <div>
            <h2 className="text-xs font-bold text-white uppercase tracking-[0.3em] mb-4">Infrastructure</h2>
            <h3 className="text-3xl font-bold text-white tracking-tight">Functional Categories</h3>
          </div>
          <Link href="/marketplace" className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-[#52525b] hover:text-white transition-colors duration-200">
            View all systems <ChevronRight className="w-4 h-4" />
          </Link>
        </div>

        <div className="grid grid-cols-2 md:grid-cols-5 gap-4">
          {categories.map((cat, i) => {
            const Icon = cat.icon;
            return (
              <motion.div
                key={cat.name}
                initial={{ opacity: 0, y: 10 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.05, duration: 0.5, ease: [0.16, 1, 0.3, 1] }}
              >
                <Link
                  href={`/marketplace?category=${encodeURIComponent(cat.name)}`}
                  className="flex flex-col items-center text-center gap-6 p-10 rounded-lg border border-white/5 bg-[#18181b]/50 hover:bg-white/5 hover:border-white/10 transition-all duration-300 group"
                >
                  <Icon className="w-6 h-6 text-[#3f3f46] group-hover:text-white transition-colors duration-300" />
                  <span className="text-[10px] font-bold uppercase tracking-[0.2em] text-[#52525b] group-hover:text-white transition-colors duration-300">{cat.name}</span>
                </Link>
              </motion.div>
            );
          })}
        </div>
      </section>

      {/* Recent Additions */}
      <section className="py-32 container mx-auto px-6 max-w-7xl border-t border-white/5 bg-[#18181b]/20">
        <div className="flex flex-col md:flex-row md:items-end justify-between mb-16 gap-6">
          <div>
            <h2 className="text-xs font-bold text-white uppercase tracking-[0.3em] mb-4">Network Activity</h2>
            <h3 className="text-3xl font-bold text-white tracking-tight">Recent Deployments</h3>
          </div>
          <Link href="/marketplace" className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-[#52525b] hover:text-white transition-colors duration-200">
            Explore index <ChevronRight className="w-4 h-4" />
          </Link>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          {mockAgents.slice(0, 3).map((agent, i) => (
            <AgentCard key={agent.id} agent={agent} index={i} />
          ))}
        </div>
      </section>

      {/* Protocol Specs */}
      <section className="py-32 container mx-auto px-6 max-w-7xl border-t border-white/5">
        <div className="mb-20 text-center max-w-3xl mx-auto">
          <h2 className="text-xs font-bold text-white uppercase tracking-[0.3em] mb-4">Performance</h2>
          <h3 className="text-3xl font-bold text-white tracking-tight mb-6">Protocol Specifications</h3>
          <p className="text-[#52525b] text-lg leading-relaxed">
            Built on standard blockchain primitives for deterministic reliability and cryptographic verification.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-12">
          {whySolana.map((item, i) => {
            const Icon = item.icon;
            return (
              <motion.div
                key={item.title}
                initial={{ opacity: 0, y: 10 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.1, duration: 0.5, ease: [0.16, 1, 0.3, 1] }}
                className="text-center group"
              >
                <div className="w-12 h-12 bg-white/5 rounded-full flex items-center justify-center mx-auto mb-8 border border-white/5 group-hover:border-white/20 transition-all duration-300">
                  <Icon className="w-5 h-5 text-white" />
                </div>
                <h3 className="text-xs font-bold text-white uppercase tracking-[0.2em] mb-4">{item.title}</h3>
                <p className="text-[#52525b] leading-relaxed text-sm group-hover:text-[#71717a] transition-colors">{item.description}</p>
              </motion.div>
            );
          })}
        </div>
      </section>
    </div>
  );
}
